// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlite

import ()

type LastLayout struct {
	App     string
	Device  string
	Code    string
	Variant string
}

type SchemaMigration struct {
	Version interface{}
	Dirty   *bool
}

type SqliteMaster struct {
	Type     *string
	Name     *string
	TblName  *string
	Rootpage *int64
	Sql      *string
}
